events {
    worker_connections 1024;
}

http {

    keepalive_timeout 300;
    proxy_read_timeout 300;
    proxy_connect_timeout 300;
    proxy_send_timeout 300;
    send_timeout 300;

    ssl_protocols TLSv1.2 TLSv1.3;  # Sadece TLS 1.2 ve üstünü izin veriyoruz.
    ssl_prefer_server_ciphers on;   # Sunucu tarafından belirlenen şifrelemeleri tercih ediyoruz.
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384';  # Güçlü şifreleme algoritmaları
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    server {
        listen 443 ssl;
        #listen 80;
        ssl_certificate /etc/ssl/private/cert.crt;
        ssl_certificate_key /etc/ssl/private/key.key;

        server_name joywhite365.com;

        location / {
            proxy_pass http://joywhite365-web:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

